export const DEFAULT_CANVAS_SIZE = { width: 816, height: 1056, backgroundColor: '#ffffff' };

export const DEFAULT_ELEMENT_PROPS = {
  rect:     { type:'rect',     x:200, y:200, width:150, height:100, fill:'#c084fc', stroke:'', strokeWidth:0, cornerRadius:0, opacity:1, rotation:0 },
  circle:   { type:'circle',   x:200, y:200, width:120, height:120, fill:'#818cf8', stroke:'', strokeWidth:0, opacity:1, rotation:0 },
  triangle: { type:'triangle', x:200, y:200, width:120, height:120, fill:'#34d399', stroke:'', strokeWidth:0, opacity:1, rotation:0 },
  star:     { type:'star',     x:200, y:200, width:120, height:120, fill:'#fbbf24', stroke:'', strokeWidth:0, opacity:1, rotation:0 },
  pentagon: { type:'pentagon', x:200, y:200, width:120, height:120, fill:'#f472b6', stroke:'', strokeWidth:0, opacity:1, rotation:0 },
  heart:    { type:'heart',    x:200, y:200, width:120, height:120, fill:'#ec4899', stroke:'', strokeWidth:0, opacity:1, rotation:0 },
  diamond:  { type:'diamond',  x:200, y:200, width:120, height:120, fill:'#a78bfa', stroke:'', strokeWidth:0, opacity:1, rotation:0 },
  line:     { type:'line',     x:150, y:300, width:200, height:0,   stroke:'#1e293b', strokeWidth:3, dash:[], opacity:1, rotation:0 },
  arrow:    { type:'arrow',    x:150, y:300, width:200, height:0,   stroke:'#1e293b', strokeWidth:3, opacity:1, rotation:0 },
  text:     { type:'text',     x:100, y:100, width:300, height:60,  text:'Double-click to edit', fontSize:24, fontFamily:'Inter', fontStyle:'normal', fill:'#1e293b', align:'left', opacity:1, rotation:0 },
  image:    { type:'image',    x:100, y:100, width:300, height:300, src:'', opacity:1, rotation:0 },
};

export const CANVAS_PRESETS = [
  { name: 'A4 Poster',         width: 816,  height: 1056 },
  { name: 'Presentation 16:9', width: 960,  height: 540  },
  { name: 'Instagram Post',    width: 600,  height: 600  },
  { name: 'Twitter Banner',    width: 1000, height: 333  },
  { name: 'Business Card',     width: 504,  height: 288  },
  { name: 'Facebook Cover',    width: 820,  height: 312  },
];

export const FONT_PAIRS = [
  { heading: 'Playfair Display', body: 'Lato' },
  { heading: 'Montserrat',       body: 'Open Sans' },
  { heading: 'Raleway',          body: 'Merriweather' },
  { heading: 'Oswald',           body: 'Roboto' },
  { heading: 'Dancing Script',   body: 'Inter' },
  { heading: 'Bebas Neue',       body: 'Inter' },
];

export const GRADIENT_PRESETS = [
  { name: 'Purple Pink',  colors: ['#7c3aed','#ec4899'] },
  { name: 'Blue Cyan',    colors: ['#2563eb','#06b6d4'] },
  { name: 'Orange Yellow',colors: ['#ea580c','#eab308'] },
  { name: 'Green Teal',   colors: ['#16a34a','#0d9488'] },
  { name: 'Red Orange',   colors: ['#dc2626','#ea580c'] },
  { name: 'Dark Navy',    colors: ['#1e1b4b','#312e81'] },
];

export const BACKGROUND_COLORS = [
  '#ffffff','#f8fafc','#f1f5f9','#e2e8f0','#cbd5e1',
  '#fef9c3','#fef3c7','#fde68a','#fed7aa','#fecaca',
  '#d1fae5','#a7f3d0','#99f6e4','#bfdbfe','#ddd6fe',
  '#fbcfe8','#1e293b','#0f172a','#18181b','#111827',
];

export const CHART_DEFAULTS = {
  bar: {
    type: 'chart',
    chartType: 'bar',
    x: 80, y: 80, width: 500, height: 320,
    rotation: 0, opacity: 1,
    title: 'Bar Chart',
    showLegend: true,
    showGrid: true,
    showTooltip: true,
    colorScheme: 'purple',
    variant: 'grouped',
    data: [
      { label: 'Q1', series1: 40, series2: 24 },
      { label: 'Q2', series1: 55, series2: 38 },
      { label: 'Q3', series1: 67, series2: 43 },
      { label: 'Q4', series1: 80, series2: 56 },
    ],
    series: [
      { key: 'series1', name: 'Series 1', color: '#7c3aed' },
      { key: 'series2', name: 'Series 2', color: '#a78bfa' },
    ],
  },
  line: {
    type: 'chart', chartType: 'line',
    x: 80, y: 80, width: 500, height: 320,
    rotation: 0, opacity: 1,
    title: 'Line Chart',
    showLegend: true, showGrid: true,
    variant: 'linear',
    colorScheme: 'purple',
    data: [
      { label: 'Jan', series1: 30, series2: 20 },
      { label: 'Feb', series1: 45, series2: 35 },
      { label: 'Mar', series1: 38, series2: 42 },
      { label: 'Apr', series1: 60, series2: 38 },
      { label: 'May', series1: 55, series2: 50 },
      { label: 'Jun', series1: 72, series2: 55 },
    ],
    series: [
      { key: 'series1', name: 'Series 1', color: '#7c3aed' },
      { key: 'series2', name: 'Series 2', color: '#06b6d4' },
    ],
  },
  area: {
    type: 'chart', chartType: 'area',
    x: 80, y: 80, width: 500, height: 320,
    rotation: 0, opacity: 1,
    title: 'Area Chart',
    showLegend: true, showGrid: true,
    variant: 'stacked',
    colorScheme: 'purple',
    data: [
      { label: 'Jan', series1: 40, series2: 24 },
      { label: 'Feb', series1: 55, series2: 38 },
      { label: 'Mar', series1: 47, series2: 42 },
      { label: 'Apr', series1: 68, series2: 30 },
      { label: 'May', series1: 60, series2: 45 },
    ],
    series: [
      { key: 'series1', name: 'Series 1', color: '#7c3aed' },
      { key: 'series2', name: 'Series 2', color: '#a78bfa' },
    ],
  },
  pie: {
    type: 'chart', chartType: 'pie',
    x: 80, y: 80, width: 400, height: 320,
    rotation: 0, opacity: 1,
    title: 'Pie Chart',
    showLegend: true,
    variant: 'pie',
    colorScheme: 'purple',
    data: [
      { label: 'Category A', value: 35, color: '#7c3aed' },
      { label: 'Category B', value: 28, color: '#06b6d4' },
      { label: 'Category C', value: 20, color: '#10b981' },
      { label: 'Category D', value: 17, color: '#f59e0b' },
    ],
  },
  scatter: {
    type: 'chart', chartType: 'scatter',
    x: 80, y: 80, width: 500, height: 320,
    rotation: 0, opacity: 1,
    title: 'Scatter Plot',
    showLegend: true, showGrid: true,
    colorScheme: 'purple',
    data: [
      { x: 10, y: 30, z: 200 },
      { x: 30, y: 45, z: 300 },
      { x: 50, y: 20, z: 150 },
      { x: 70, y: 60, z: 400 },
      { x: 90, y: 40, z: 250 },
      { x: 20, y: 55, z: 180 },
      { x: 60, y: 75, z: 350 },
    ],
    series: [{ key: 'data', name: 'Data Points', color: '#7c3aed' }],
  },
  radar: {
    type: 'chart', chartType: 'radar',
    x: 80, y: 80, width: 400, height: 360,
    rotation: 0, opacity: 1,
    title: 'Radar Chart',
    showLegend: true,
    colorScheme: 'purple',
    data: [
      { label: 'Speed', series1: 80, series2: 60 },
      { label: 'Power', series1: 65, series2: 90 },
      { label: 'Range', series1: 90, series2: 70 },
      { label: 'Accuracy', series1: 75, series2: 85 },
      { label: 'Endurance', series1: 55, series2: 75 },
    ],
    series: [
      { key: 'series1', name: 'Product A', color: '#7c3aed' },
      { key: 'series2', name: 'Product B', color: '#06b6d4' },
    ],
  },
  funnel: {
    type: 'chart', chartType: 'funnel',
    x: 80, y: 80, width: 400, height: 340,
    rotation: 0, opacity: 1,
    title: 'Funnel Chart',
    showLegend: false,
    colorScheme: 'purple',
    data: [
      { label: 'Visitors', value: 5000, color: '#7c3aed' },
      { label: 'Leads', value: 3200, color: '#8b5cf6' },
      { label: 'Prospects', value: 1800, color: '#a78bfa' },
      { label: 'Customers', value: 900, color: '#c4b5fd' },
      { label: 'Retained', value: 500, color: '#ddd6fe' },
    ],
  },
  treemap: {
    type: 'chart', chartType: 'treemap',
    x: 80, y: 80, width: 500, height: 340,
    rotation: 0, opacity: 1,
    title: 'Treemap',
    showLegend: false,
    colorScheme: 'purple',
    data: [
      { label: 'Product A', value: 400 },
      { label: 'Product B', value: 300 },
      { label: 'Product C', value: 200 },
      { label: 'Product D', value: 150 },
      { label: 'Product E', value: 100 },
      { label: 'Product F', value: 80 },
    ],
  },
  radialBar: {
    type: 'chart', chartType: 'radialBar',
    x: 80, y: 80, width: 400, height: 360,
    rotation: 0, opacity: 1,
    title: 'Radial Bar',
    showLegend: true,
    colorScheme: 'purple',
    data: [
      { label: 'Design', value: 85, color: '#7c3aed' },
      { label: 'Development', value: 72, color: '#8b5cf6' },
      { label: 'Marketing', value: 60, color: '#a78bfa' },
      { label: 'Sales', value: 91, color: '#06b6d4' },
    ],
  },
  progress: {
    type: 'chart', chartType: 'progress',
    x: 80, y: 80, width: 280, height: 280,
    rotation: 0, opacity: 1,
    title: 'Progress',
    variant: 'ring',
    value: 72,
    color: '#7c3aed',
    trackColor: '#e9d5ff',
    showLabel: true,
    strokeWidth: 20,
  },
  waterfall: {
    type: 'chart', chartType: 'waterfall',
    x: 80, y: 80, width: 500, height: 320,
    rotation: 0, opacity: 1,
    title: 'Waterfall Chart',
    showLegend: false, showGrid: true,
    colorScheme: 'purple',
    data: [
      { label: 'Start', value: 1000, type: 'total' },
      { label: 'Sales', value: 400, type: 'positive' },
      { label: 'Costs', value: -150, type: 'negative' },
      { label: 'Tax', value: -80, type: 'negative' },
      { label: 'Other', value: 60, type: 'positive' },
      { label: 'End', value: 1230, type: 'total' },
    ],
  },
  stackedBar: {
    type: 'chart',
    chartType: 'bar',
    x: 80, y: 80, width: 500, height: 320,
    rotation: 0, opacity: 1,
    title: 'Stacked Bar Chart',
    showLegend: true,
    showGrid: true,
    showTooltip: true,
    colorScheme: 'purple',
    variant: 'stacked',
    data: [
      { label: 'Q1', series1: 40, series2: 24 },
      { label: 'Q2', series1: 55, series2: 38 },
      { label: 'Q3', series1: 67, series2: 43 },
      { label: 'Q4', series1: 80, series2: 56 },
    ],
    series: [
      { key: 'series1', name: 'Series 1', color: '#7c3aed' },
      { key: 'series2', name: 'Series 2', color: '#a78bfa' },
    ],
  },
  stackedBar100: {
    type: 'chart', chartType: 'bar',
    x: 80, y: 80, width: 500, height: 320,
    rotation: 0, opacity: 1,
    title: '100% Stacked Bar',
    showLegend: true, showGrid: true,
    variant: 'stacked100',
    colorScheme: 'purple',
    data: [
      { label: 'Q1', a: 40, b: 35, c: 25 },
      { label: 'Q2', a: 35, b: 40, c: 25 },
      { label: 'Q3', a: 30, b: 30, c: 40 },
      { label: 'Q4', a: 45, b: 25, c: 30 },
    ],
    series: [
      { key: 'a', name: 'Product A', color: '#7c3aed' },
      { key: 'b', name: 'Product B', color: '#06b6d4' },
      { key: 'c', name: 'Product C', color: '#10b981' },
    ],
  },
  multiLine: {
    type: 'chart', chartType: 'line',
    x: 80, y: 80, width: 500, height: 320,
    rotation: 0, opacity: 1,
    title: 'Multi-Line Chart',
    showLegend: true, showGrid: true,
    variant: 'smooth',
    colorScheme: 'teal',
    data: [
      { label: 'Jan', a: 30, b: 20, c: 45 },
      { label: 'Feb', a: 45, b: 35, c: 38 },
      { label: 'Mar', a: 38, b: 42, c: 52 },
      { label: 'Apr', a: 60, b: 38, c: 41 },
      { label: 'May', a: 55, b: 50, c: 60 },
      { label: 'Jun', a: 72, b: 55, c: 68 },
    ],
    series: [
      { key: 'a', name: 'Series A', color: '#0d9488' },
      { key: 'b', name: 'Series B', color: '#06b6d4' },
      { key: 'c', name: 'Series C', color: '#8b5cf6' },
    ],
  },
  composed: {
    type: 'chart', chartType: 'composed',
    x: 80, y: 80, width: 500, height: 320,
    rotation: 0, opacity: 1,
    title: 'Bar + Line Combo',
    showLegend: true, showGrid: true,
    colorScheme: 'purple',
    data: [
      { label: 'Q1', bars: 40, line: 30 },
      { label: 'Q2', bars: 55, line: 45 },
      { label: 'Q3', bars: 67, line: 58 },
      { label: 'Q4', bars: 80, line: 72 },
    ],
    series: [
      { key: 'bars', name: 'Revenue', color: '#7c3aed', renderAs: 'bar' },
      { key: 'line', name: 'Margin %', color: '#06b6d4', renderAs: 'line' },
    ],
  },
};

export const CHART_COLOR_SCHEMES = {
  purple: ['#7c3aed', '#8b5cf6', '#a78bfa', '#c4b5fd', '#ddd6fe', '#ede9fe'],
  blue: ['#2563eb', '#3b82f6', '#60a5fa', '#93c5fd', '#bfdbfe', '#dbeafe'],
  teal: ['#0d9488', '#14b8a6', '#2dd4bf', '#5eead4', '#99f6e4', '#ccfbf1'],
  warm: ['#dc2626', '#ea580c', '#d97706', '#ca8a04', '#65a30d', '#16a34a'],
  mono: ['#1e293b', '#334155', '#475569', '#64748b', '#94a3b8', '#cbd5e1'],
};

export const STAT_BLOCK_DEFAULTS = {
  kpi: {
    type: 'statBlock',
    subtype: 'kpi',
    x: 80,
    y: 80,
    width: 220,
    height: 130,
    rotation: 0,
    opacity: 1,
    value: '$2.4M',
    label: 'Annual Revenue',
    trend: '+34%',
    trendDir: 'up',
    trendLabel: 'vs last year',
    accentColor: '#7c3aed',
    bgColor: '#ffffff',
    textColor: '#1e293b',
    style: 'card',
  },
  comparison: {
    type: 'statBlock',
    subtype: 'comparison',
    x: 80,
    y: 80,
    width: 340,
    height: 120,
    rotation: 0,
    opacity: 1,
    leftValue: '68%',
    leftLabel: 'With Us',
    rightValue: '34%',
    rightLabel: 'Industry Avg',
    vsLabel: 'vs',
    accentColor: '#7c3aed',
    bgColor: '#ffffff',
    textColor: '#1e293b',
    style: 'card',
  },
  progressStat: {
    type: 'statBlock',
    subtype: 'progressStat',
    x: 80,
    y: 80,
    width: 280,
    height: 100,
    rotation: 0,
    opacity: 1,
    value: 72,
    label: 'Goal Completion',
    sublabel: '72 of 100 milestones',
    accentColor: '#7c3aed',
    trackColor: '#e9d5ff',
    bgColor: '#ffffff',
    textColor: '#1e293b',
    style: 'card',
  },
  rankedList: {
    type: 'statBlock',
    subtype: 'rankedList',
    x: 80,
    y: 80,
    width: 300,
    height: 200,
    rotation: 0,
    opacity: 1,
    title: 'Top Markets',
    items: [
      { label: 'North America', value: 52, color: '#7c3aed' },
      { label: 'Europe', value: 31, color: '#8b5cf6' },
      { label: 'Asia Pacific', value: 17, color: '#a78bfa' },
    ],
    bgColor: '#ffffff',
    textColor: '#1e293b',
    style: 'card',
  },
  iconStat: {
    type: 'statBlock',
    subtype: 'iconStat',
    x: 80,
    y: 80,
    width: 180,
    height: 160,
    rotation: 0,
    opacity: 1,
    iconName: 'Users',
    value: '12,400',
    label: 'Active Users',
    accentColor: '#7c3aed',
    bgColor: '#f5f3ff',
    textColor: '#1e293b',
    style: 'card',
  },
};

export const TIMELINE_DEFAULTS = {
  horizontal: {
    type: 'timeline',
    subtype: 'horizontal',
    x: 40,
    y: 160,
    width: 880,
    height: 200,
    rotation: 0,
    opacity: 1,
    accentColor: '#7c3aed',
    bgColor: 'transparent',
    lineColor: '#e2e8f0',
    style: 'dots',
    items: [
      { label: 'Q1 2024', sublabel: 'Foundation', description: 'Product built, team hired', done: true },
      { label: 'Q2 2024', sublabel: 'Launch', description: 'Public launch, 500 users', done: true },
      { label: 'Q3 2024', sublabel: 'Growth', description: 'Series A closed, 5K users', done: true },
      { label: 'Q4 2024', sublabel: 'Scale', description: '12K users, 3 new markets', done: false },
      { label: 'Q1 2025', sublabel: 'Expand', description: 'IPO preparation begins', done: false },
    ],
  },
  vertical: {
    type: 'timeline',
    subtype: 'vertical',
    x: 80,
    y: 60,
    width: 360,
    height: 420,
    rotation: 0,
    opacity: 1,
    accentColor: '#7c3aed',
    bgColor: 'transparent',
    lineColor: '#e2e8f0',
    style: 'dots',
    items: [
      { label: 'Phase 1', sublabel: 'Months 1-3', description: 'Foundation and setup' },
      { label: 'Phase 2', sublabel: 'Months 4-6', description: 'Build and validate' },
      { label: 'Phase 3', sublabel: 'Months 7-9', description: 'Launch and iterate' },
      { label: 'Phase 4', sublabel: 'Months 10-12', description: 'Scale and optimise' },
    ],
  },
  steps: {
    type: 'timeline',
    subtype: 'steps',
    x: 40,
    y: 120,
    width: 880,
    height: 180,
    rotation: 0,
    opacity: 1,
    accentColor: '#7c3aed',
    bgColor: 'transparent',
    lineColor: '#e2e8f0',
    style: 'numbered',
    items: [
      { label: 'Connect', description: 'Link your data sources in minutes' },
      { label: 'Configure', description: 'Set rules with intelligent defaults' },
      { label: 'Launch', description: 'Go live with one click' },
      { label: 'Monitor', description: 'Track performance in real time' },
    ],
  },
};

export const CALLOUT_DEFAULTS = {
  'bottom-left': { type: 'callout', x: 100, y: 100, width: 220, height: 120, rotation: 0, opacity: 1, fill: '#7c3aed', stroke: null, strokeWidth: 0, tailDir: 'bottom-left', text: 'Callout text here', fontSize: 14, textColor: '#ffffff', fontFamily: 'Inter', cornerRadius: 10 },
  'bottom-right': { type: 'callout', x: 100, y: 100, width: 220, height: 120, rotation: 0, opacity: 1, fill: '#7c3aed', stroke: null, strokeWidth: 0, tailDir: 'bottom-right', text: 'Callout text here', fontSize: 14, textColor: '#ffffff', fontFamily: 'Inter', cornerRadius: 10 },
  'top-left': { type: 'callout', x: 100, y: 100, width: 220, height: 120, rotation: 0, opacity: 1, fill: '#7c3aed', stroke: null, strokeWidth: 0, tailDir: 'top-left', text: 'Callout text here', fontSize: 14, textColor: '#ffffff', fontFamily: 'Inter', cornerRadius: 10 },
  'top-right': { type: 'callout', x: 100, y: 100, width: 220, height: 120, rotation: 0, opacity: 1, fill: '#7c3aed', stroke: null, strokeWidth: 0, tailDir: 'top-right', text: 'Callout text here', fontSize: 14, textColor: '#ffffff', fontFamily: 'Inter', cornerRadius: 10 },
  left: { type: 'callout', x: 100, y: 100, width: 220, height: 120, rotation: 0, opacity: 1, fill: '#7c3aed', stroke: null, strokeWidth: 0, tailDir: 'left', text: 'Callout text here', fontSize: 14, textColor: '#ffffff', fontFamily: 'Inter', cornerRadius: 10 },
  right: { type: 'callout', x: 100, y: 100, width: 220, height: 120, rotation: 0, opacity: 1, fill: '#7c3aed', stroke: null, strokeWidth: 0, tailDir: 'right', text: 'Callout text here', fontSize: 14, textColor: '#ffffff', fontFamily: 'Inter', cornerRadius: 10 },
};

export const FRAME_DEFAULTS = {
  circle: { type: 'frame', frameShape: 'circle', x: 100, y: 100, width: 200, height: 200, rotation: 0, opacity: 1, imageId: null, src: null, imageFit: 'cover', imageOffsetX: 0, imageOffsetY: 0, imageScale: 1, strokeColor: '#7c3aed', strokeWidth: 0 },
  roundedRect: { type: 'frame', frameShape: 'roundedRect', x: 100, y: 100, width: 200, height: 200, rotation: 0, opacity: 1, cornerRadius: 20, imageId: null, src: null, imageFit: 'cover', imageOffsetX: 0, imageOffsetY: 0, imageScale: 1, strokeColor: '#7c3aed', strokeWidth: 0 },
  hexagon: { type: 'frame', frameShape: 'hexagon', x: 100, y: 100, width: 200, height: 200, rotation: 0, opacity: 1, imageId: null, src: null, imageFit: 'cover', imageOffsetX: 0, imageOffsetY: 0, imageScale: 1, strokeColor: '#7c3aed', strokeWidth: 0 },
  diamond: { type: 'frame', frameShape: 'diamond', x: 100, y: 100, width: 200, height: 200, rotation: 0, opacity: 1, imageId: null, src: null, imageFit: 'cover', imageOffsetX: 0, imageOffsetY: 0, imageScale: 1, strokeColor: '#7c3aed', strokeWidth: 0 },
  triangle: { type: 'frame', frameShape: 'triangle', x: 100, y: 100, width: 200, height: 200, rotation: 0, opacity: 1, imageId: null, src: null, imageFit: 'cover', imageOffsetX: 0, imageOffsetY: 0, imageScale: 1, strokeColor: '#7c3aed', strokeWidth: 0 },
};

export const FLOWCHART_DEFAULTS = {
  process: { type: 'flowchart', subtype: 'process', x: 100, y: 100, width: 160, height: 80, rotation: 0, opacity: 1, fill: '#ede9fe', stroke: '#7c3aed', strokeWidth: 2, text: 'Process Step', fontSize: 13, textColor: '#1e293b', fontFamily: 'Inter' },
  decision: { type: 'flowchart', subtype: 'decision', x: 100, y: 100, width: 160, height: 80, rotation: 0, opacity: 1, fill: '#fef3c7', stroke: '#f59e0b', strokeWidth: 2, text: 'Decision?', fontSize: 13, textColor: '#1e293b', fontFamily: 'Inter' },
  terminal: { type: 'flowchart', subtype: 'terminal', x: 100, y: 100, width: 160, height: 80, rotation: 0, opacity: 1, fill: '#dcfce7', stroke: '#16a34a', strokeWidth: 2, text: 'Start', fontSize: 13, textColor: '#1e293b', fontFamily: 'Inter' },
  document: { type: 'flowchart', subtype: 'document', x: 100, y: 100, width: 160, height: 80, rotation: 0, opacity: 1, fill: '#dbeafe', stroke: '#2563eb', strokeWidth: 2, text: 'Document', fontSize: 13, textColor: '#1e293b', fontFamily: 'Inter' },
  database: { type: 'flowchart', subtype: 'database', x: 100, y: 100, width: 160, height: 80, rotation: 0, opacity: 1, fill: '#e0f2fe', stroke: '#0891b2', strokeWidth: 2, text: 'Database', fontSize: 13, textColor: '#1e293b', fontFamily: 'Inter' },
  parallelogram: { type: 'flowchart', subtype: 'parallelogram', x: 100, y: 100, width: 160, height: 80, rotation: 0, opacity: 1, fill: '#fce7f3', stroke: '#ec4899', strokeWidth: 2, text: 'Input', fontSize: 13, textColor: '#1e293b', fontFamily: 'Inter' },
  hexagon: { type: 'flowchart', subtype: 'hexagon', x: 100, y: 100, width: 160, height: 80, rotation: 0, opacity: 1, fill: '#f3e8ff', stroke: '#9333ea', strokeWidth: 2, text: 'Prepare', fontSize: 13, textColor: '#1e293b', fontFamily: 'Inter' },
  cloud: { type: 'flowchart', subtype: 'cloud', x: 100, y: 100, width: 160, height: 80, rotation: 0, opacity: 1, fill: '#e0f7fa', stroke: '#06b6d4', strokeWidth: 2, text: 'Cloud', fontSize: 13, textColor: '#1e293b', fontFamily: 'Inter' },
};
