export const STARTER_TEMPLATES = [
  {
    name: "Business Card",
    canvasSize: { width: 504, height: 288, backgroundColor: "#1e1b4b" },
    elements: [
      {
        type: "rect",
        x: 0, y: 0, width: 504, height: 288,
        fill: "#1e1b4b", opacity: 1, rotation: 0,
      },
      {
        type: "rect",
        x: 0, y: 220, width: 504, height: 68,
        fill: "#7c3aed", opacity: 1, rotation: 0,
      },
      {
        type: "text",
        x: 40, y: 60, width: 300,
        text: "Jane Smith",
        fontSize: 36, fontFamily: "Montserrat",
        fontStyle: "bold", fill: "#ffffff",
        opacity: 1, rotation: 0,
      },
      {
        type: "text",
        x: 40, y: 110, width: 300,
        text: "Creative Director",
        fontSize: 16, fontFamily: "Inter",
        fontStyle: "normal", fill: "#a5b4fc",
        opacity: 1, rotation: 0,
      },
      {
        type: "text",
        x: 40, y: 235, width: 420,
        text: "jane@company.com  ·  +1 (555) 000-0000",
        fontSize: 13, fontFamily: "Inter",
        fontStyle: "normal", fill: "#ffffff",
        opacity: 1, rotation: 0,
      },
    ],
  },
  {
    name: "Social Post",
    canvasSize: { width: 600, height: 600, backgroundColor: "#faf5ff" },
    elements: [
      {
        type: "rect",
        x: 0, y: 0, width: 600, height: 600,
        fillLinearGradientStartPoint: { x: 0, y: 0 },
        fillLinearGradientEndPoint: { x: 600, y: 600 },
        fillLinearGradientColorStops: [0, "#7c3aed", 1, "#ec4899"],
        opacity: 1, rotation: 0,
      },
      {
        type: "circle",
        x: 200, y: 120, width: 200, height: 200,
        fill: "rgba(255,255,255,0.15)",
        opacity: 1, rotation: 0,
      },
      {
        type: "text",
        x: 60, y: 250, width: 480,
        text: "YOUR BIG\nANNOUNCEMENT",
        fontSize: 56, fontFamily: "Montserrat",
        fontStyle: "bold", fill: "#ffffff",
        align: "center", opacity: 1, rotation: 0,
      },
      {
        type: "text",
        x: 60, y: 420, width: 480,
        text: "Add your subtitle or call to action here",
        fontSize: 20, fontFamily: "Inter",
        fontStyle: "normal", fill: "rgba(255,255,255,0.8)",
        align: "center", opacity: 1, rotation: 0,
      },
      {
        type: "rect",
        x: 200, y: 490, width: 200, height: 46,
        fill: "#ffffff", cornerRadius: 23,
        opacity: 1, rotation: 0,
      },
      {
        type: "text",
        x: 200, y: 503, width: 200,
        text: "Learn More",
        fontSize: 16, fontFamily: "Inter",
        fontStyle: "bold", fill: "#7c3aed",
        align: "center", opacity: 1, rotation: 0,
      },
    ],
  },
  {
    name: "Presentation Slide",
    canvasSize: { width: 960, height: 540, backgroundColor: "#ffffff" },
    elements: [
      {
        type: "rect",
        x: 0, y: 0, width: 8, height: 540,
        fill: "#7c3aed", opacity: 1, rotation: 0,
      },
      {
        type: "rect",
        x: 0, y: 0, width: 960, height: 3,
        fill: "#7c3aed", opacity: 1, rotation: 0,
      },
      {
        type: "text",
        x: 60, y: 120, width: 720,
        text: "Presentation Title",
        fontSize: 64, fontFamily: "Playfair Display",
        fontStyle: "bold", fill: "#1e293b",
        opacity: 1, rotation: 0,
      },
      {
        type: "text",
        x: 60, y: 220, width: 600,
        text: "Your subtitle goes here — make it count",
        fontSize: 24, fontFamily: "Inter",
        fontStyle: "normal", fill: "#64748b",
        opacity: 1, rotation: 0,
      },
      {
        type: "rect",
        x: 60, y: 310, width: 120, height: 4,
        fill: "#7c3aed", opacity: 1, rotation: 0,
      },
      {
        type: "text",
        x: 60, y: 340, width: 400,
        text: "Presenter Name  ·  Date",
        fontSize: 16, fontFamily: "Inter",
        fontStyle: "normal", fill: "#94a3b8",
        opacity: 1, rotation: 0,
      },
    ],
  },
];
